name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '*'  

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      
      - name: Terraform Init
        run: terraform init
        working-directory: eksamen-2024-main/infra  

      
      - name: Terraform Plan or Apply
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            terraform apply -auto-approve
          else
            terraform plan
          fi
        working-directory: eksamen-2024-main/infra  
